#!/usr/bin/env python3


print("  __________________  ")
print(" (                  )  ")
print(" (       Hello      )  ")
print(" (       Lovely     )  ")
print(" (       Human!     ) ")
print("  ------------------  ")
print("      o  ")
print("       o  ")
print("          oO)-.                       .-(Oo  ")
print("         /__  _\                     /_  __\  ")
print("         \  \(  |     ()~()         |  )/  /  ")
print("          \__|\ |    (-___-)        | /|__/  ")
print("          '  '--'    ==`-'==        '--'  '  ")


print("           /^\/^\    ")
print("         _|__|  O|    ")
print("\/     /~     \_/ \    ")
print(" \____|__________/  \    ")
print("        \_______      \    ")
print("                `\     \                 \    ")
print("                  |     |                  \    ")
print("                /      /                    \    ")
print("                /     /                       \\    ")
print("              /      /                         \ \    ")
print("             /     /                            \  \    ")
print("           /     /             _----_            \   \    ")
print("          /     /           _-~      ~-_         |   |    ")
print("         (      (        _-~    _--_    ~-_     _/   |    ")
print("          \      ~-____-~    _-~    ~-_    ~-_-~    /    ")
print("            ~-_           _-~          ~-_       _-~    ")
print("               ~--______-~                ~-___-~    ")